coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%

ignore:
  - "src/main/java/com/myproject/autopartsestoresystem/test/*"
  - "src/main/java/com/myproject/autopartsestoresystem/exception/*"
