CREATE TABLE IF NOT EXISTS brands
(
    id   SMALLINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL

);

CREATE TABLE IF NOT EXISTS models
(
    id       SMALLINT PRIMARY KEY AUTO_INCREMENT,
    name     VARCHAR(50) NOT NULL,
    brand_id SMALLINT    NOT NULL,

    CONSTRAINT uq_model UNIQUE KEY (brand_id, name),
    CONSTRAINT fk_model_brand FOREIGN KEY (brand_id) REFERENCES AUTO_PARTS.brands (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vehicles(
    id MEDIUMINT PRIMARY KEY AUTO_INCREMENT,
    engine_type VARCHAR(120) NOT NULL,
    series VARCHAR(120) NOT NULL,
    model_id SMALLINT NOT NULL,

    CONSTRAINT fk_vehicle_model FOREIGN KEY (model_id) REFERENCES AUTO_PARTS.models(id) ON UPDATE CASCADE ON DELETE RESTRICT

);